### ISSUE TITLE
Expr: xor operator crashes VapourSynth

### ISSUE THREAD

**Issue by Setsugennoao** [AkarinVS/vapoursynth-plugin#14]
Hello Akarin, I recently updated one of my functions substituting the old `* 0 <` with `xor` ([#d9345df](https://github.com/Irrational-Encoding-Wizardry/vs-rgtools/commit/5e20a18a4a008a38fa73f5470b1e85d16e30adce#diff-79206779539d1c8820572a3f1541843b6309ce06a70b06724bba03b15eeac2b6L102-R107)).
Today, running a filterchain it crashed (can reproduce with [this](https://github.com/Setsugennoao/Encoding-Scripts/blob/master/Setsu-Raws/Summer%20Time%20Rendering%20(WEB)/smtr_16.vpy)).
After some debugging and wasting time isolating filters and functions used, I found out that the edited expr in contra_dehalo was the culprit xd

EDIT: Fwiw I'm using the latest build, with dynamic pixel access, though it shouldn't change stuff, I think?

**Comment by AkarinVS** [comment]
Interesting. The handling of and/or/xor are almost exactly the same, so
it's very unlikely there are bugs that only affect xor but not and/or
(which are used much more often).
I tried a few cases, but couldn't reproduce the crash.

Could you please produce a minimal test case?

Thanks.

**Comment by Setsugennoao** [comment]
Hi! The weird fact is that I can't reproduce it without that video and filterchain, so there must be something very strange happening :/
Will look a bit more into it later, some months have passed, after all.

**Comment by Setsugennoao** [comment]
v0.96f seems to have fixed this, thanks!
