### ISSUE TITLE
support for llvm 14

### ISSUE THREAD

**Issue by damian101** [AkarinVS/vapoursynth-plugin#15]
can't build on Arch because llvm 14 is not supported

**Comment by AkarinVS** [comment]
does Arch support installing multiple llvm versions?
llvm 14 changed some old APIs and it might take some time to adapt the code to it.

**Comment by damian101** [comment]
> does Arch support installing multiple llvm versions? llvm 14 changed some old APIs and it might take some time to adapt the code to it.

Yes, but package and installation name is different, `llvm13`/`llvm12/...`.

**Comment by damian101** [comment]
> does Arch support installing multiple llvm versions?

yes, at least llvm13 can be easily installed aside main llvm 14: https://archlinux.org/packages/extra/x86_64/llvm13/

**Comment by BlueSwordM** [comment]
So that's why it was failing to build lmao.

**Comment by AkarinVS** [comment]
The version check is meaningful. please don't override it. LLVM 14 has some incompatible APIs.

@sl1pkn07, is it possible to add the llvm < 14 version requirement to https://aur.archlinux.org/packages/vapoursynth-plugin-vsakarin-git to fix the build?
Thanks.

**Comment by sl1pkn07** [comment]
try now

**Comment by AkarinVS** [comment]
Thanks! I believe it should fix the build errors.

Will keep this issue open to track llvm 14 support (though not a top priority as llvm 13 already works well enough)

**Comment by Nalsai** [comment]
I'm on Fedora and it wouldn't build with llvm14 and 13 installed. I had to uninstall llvm14 to make it work.

**Comment by AkarinVS** [comment]
Now it supports llvm 10 - 15.
