### ISSUE TITLE
Allow to pass more clips in Expr

### ISSUE THREAD

**Issue by couleurm** [AkarinVS/vapoursynth-plugin#17]
Could it be possible to allow for more letters _(currently supports A-Z, new characters or letters could be european stuff like éöâîï, should be plenty with all combinations)_ and thus also allow for [more clips to be provided](https://github.com/AkarinVS/vapoursynth-plugin/blob/530b489435334199354c6e81b793327598a341f1/expr2/exprfilter.cpp#L1359) ?

My use case for this is having more [seamless motion blur](https://cdn.discordapp.com/attachments/824297395801554974/1026557383490666537/overwatch_by_aimslut.webm) (remember my script and sample in [VS-Classic's #7](https://github.com/AmusementClub/vapoursynth-classic/issues/7), I currently use [vs-frameblender](https://github.com/couleurm/vs-frameblender) as a backup in case user provides more than 25 weights

**Comment by AkarinVS** [comment]
Couldn't you divide the weights into multiple Expr's?
e.g.
`w0 * x + w1 * y + w2 * z` can be changed to (assuming `Expr` only allows two input clips):
```python
Expr([Expr([x, y], f"{w0} x * {w1} y * +"), z], f"x {w2} y * +"))
```

If you have a large number of clips, an expression like this will be bounded by memory bandwidth, so splitting it into multiple passes won't hurt much. Just remember to balance the size of expressions.

**Comment by AkarinVS** [comment]
Implemented. Use `srcN` to access the `N`-th clip. (N counts from 0.)
