### ISSUE TITLE
DLVFX: Invalid strengh parameter

### ISSUE THREAD

**Issue by couleurm** [AkarinVS/vapoursynth-plugin#19]
Since Selur made an issue a few days ago I've wanted to try make DLVFX work again, but encounter the same error which seems out of place

script:
```Python
from vapoursynth import core
import vapoursynth as vs

clip = core.ffms2.Source(r"D:\Video Vault\cian@60.mp4")

path = r"C:\Program Files\NVIDIA Corporation\NVIDIA Video Effects\models"
clip = core.resize.Bicubic(clip=clip, format=vs.RGBS)
OP_AR, OP_SUPERRES, OP_DENOISE = range(3)
clip = core.akarin.DLVFX(clip, op=OP_SUPERRES, scale=2, model_dir=path)
clip = core.resize.Bicubic(clip=clip, format=vs.YUV420P8, matrix=1)

clip.set_output()
```

error (I've also tried to pass strength with a bunch of different values, throws the same thing every time):
```Python
MODEL_DIR = C:\Program Files\NVIDIA Corporation\NVIDIA Video Effects\models
NvVFX set strength failed: fffffffb (The given parameter selector is not valid in this effect filter)
Script evaluation failed:
Python exception: DLVFX: failed to set strength: The given parameter selector is not valid in this effect filter

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2979, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2980, in vapoursynth._vpy_evaluate
  File "C:\Users\Dek\AppData\Local\Temp\DLVFX.py", line 10, in <module>
    clip = core.akarin.DLVFX(clip, op=OP_SUPERRES, scale=2, model_dir=path)
  File "src\cython\vapoursynth.pyx", line 2727, in vapoursynth.Function.__call__
vapoursynth.Error: DLVFX: failed to set strength: The given parameter selector is not valid in this effect filter
```

Using `OP_AR` does not throw and actually outputs a video, just like for Selur

Using `OP_DENOISE` with `strength` at 0 and 1 does not throw a Python exception, but still returns this (and no video)
```Python
MODEL_DIR = C:\Program Files\NVIDIA Corporation\NVIDIA Video Effects\models
failed VFX call NvVFX_GetU32(d->vfx, NVVFX_STATE_SIZE, &stateSizeInBytes): fffffffb (The given parameter selector is not valid in this effect filter)
```

==> Would be worth taking a look at strength to see if it does not mess some things up

**Comment by AkarinVS** [comment]
The strength issue is because latest VFX SDK changed the parameter name (from `strength` to `mode`).

I'm not yet sure about the denoise issue. The code should match the official sample code.
However, I think denoise is not very suitable as a VS plugin as denoise requires sequence access to frames (it is mainly intended for webcam denoising).

**Comment by AkarinVS** [comment]
For the strength issue, please try the newly updated https://github.com/AkarinVS/vapoursynth-plugin/releases/download/v0.96/akarin-release-lexpr-amd64-v0.96.7z build.

**Comment by couleurm** [comment]
it seems to work, will test it and DM you some results on discord if they're any interesting 👍

**Comment by AkarinVS** [comment]
Unfortunately, the `OP_DENOISE` code has never been working...
As stated earlier, it requires sequential frame processing, so it is not a good fit for VS anyway.
