### ISSUE TITLE
failed cuda call cuCtxPushCurrent(d->ctx)

### ISSUE THREAD

**Issue by Ichunjo** [AkarinVS/vapoursynth-plugin#3]
Hello

```py
upscale = core.akarin.DLISR(clip.resize.Bicubic(format=vs.RGBS), 2)
```

```
*** nvngx_dlisr NVSDK_NGX_CUDA_Init ***
*** nvngx_dlisr NVSDK_NGX_CUDA_CreateFeature ***
cuda back-end devices: <NVIDIA GeForce RTX 3070::51416>
failed cuda call cuCtxPushCurrent(d->ctx): 201
```

I installed the content of `akarin-release-lexpr-amd64-v0.70.7z` and `akarin.dlisr.v1b.7z` along side `nvngx_dlisr.dll` from `Nvidia NGX Technology`

**Comment by AkarinVS** [comment]
cuda context management is very delicate for this filter. Do you have other
GPU filters in the same vpy script?
It tends to break if DLISR is not the lone GPU filter used in a script for
reasons I can't yet explain....
(Btw, no need to install nvngx_dlisr.dll as the akarin.dlisr.dll should
suffice.)

**Comment by Ichunjo** [comment]
Thanks for the tip, indeed I was using another gpu filter (BM3D CUDA)

**Comment by AkarinVS** [comment]
I will see what I can do about this issue. It shouldn't be that sensitive to other GPU filters.
